## Find tickets with keywords ##

library(tidyverse); library(lubridate); library(tools); library (readxl)

import_files <- function(files){
  out <- data_frame()
  for (i in 1:length(files)){
    if (file_ext(files[i]) == "xlsx") { data <- readxl::read_excel(files[i])
    } else if (file_ext(files[i]) == "csv") { data <- read.csv(files[i])  # make change: convert columns on import
    } else { break }
    data$import_sheet <- str_extract(files[i], "(?<=/).*") # positive lookbehind
    out <- bind_rows(out, data)
  }
  ## add distinct('everything-but-import-sheet') line
  return(out)
}


onepos_files <- "\\\\cewp1650\\Chris Jabr Reports\\Extended Metrics 2017.csv"
Trend_Analysis_Import <- import_files(files = onepos_files)
Trend_Analysis_Import$import_sheet <- NULL
Trend_Analysis_Import <- Trend_Analysis_Import %>% distinct()


# Search for tickets by keywords

test <- Trend_Analysis_Import

test <- test %>% mutate(Trending_Issue = case_when(str_detect(`Title`, "(?i)msr") ~ "MSR",
                                                str_detect(`Title`, "(?i)printer") ~ "Printer", 
                                                str_detect(`Title`, "(?i)offline") ~ "Offline", 
                                                str_detect(`Title`, "(?i)back up battery") ~ "Battery", 
                                                str_detect(`Title`, "(?i)cash drawer") ~ "Cash Drawer", 
                                                str_detect(`Title`, "(?i)Store Balance Report") ~ "Store Balance Report", 
                                                str_detect(`Title`, "(?i)scanner") ~ "Scanner", 
                                                str_detect(`Title`, "(?i)scale") ~ "Scale", 
                                                str_detect(`Title`, "(?i)pxe") ~ "PXE", 
                                                str_detect(`Title`, "(?i)key") ~ "Keycap", 
                                                str_detect(`Title`, "(?i)sidecar") ~ "Sidecar", 
                                                str_detect(`Title`, "(?i)customer display") ~ "Customer Display", 
                                                str_detect(`Title`, "(?i)cashier display") ~ "Cashier Display", 
                                                str_detect(`Title`, "(?i)opos triad") ~ "NCR Loader", 
                                                str_detect(`Title`, "(?i)cmrc") ~ "CMRC", 
                                                str_detect(`Title`, "(?i)aloha kitchen") ~ "Aloha Kitchen", 
                                                str_detect(`Title`, "(?i)HDD") ~ "Hard drive", 
                                                str_detect(`Title`, "(?i)Prime") ~ "Prime", 
                                                str_detect(`Title`, "(?i)Missing Transaction") ~ "Sales Audit", 
                                                str_detect(`Title`, "(?i)Stuck Transaction") ~ "Stuck Transaction", 
                                                str_detect(`Title`, "(?i)MSR stylus") ~ "MSR Stylus", 
                                                str_detect(`Title`, "(?i)cleaning kit") ~ "MSR Cleaning Kit", 
                                                str_detect(`Title`, "(?i)bump bar") ~ "Aloha Bump Bar", 
                                                str_detect(`Title`, "(?i)line director") ~ "Line Director", 
                                                str_detect(`Title`, "(?i)price checker") ~ "Price Checker", 
                                                str_detect(`Title`, "(?i)pck") ~ "Price Checker", 
                                                str_detect(`Title`, "(?i)SCO") ~ "Self Checkout", 
                                                str_detect(`Title`, "(?i)Tidel") ~ "Revolution Tidel", 
                                                str_detect(`Title`, "(?i)mainboard") ~ "Mainboard", 
                                                str_detect(`Title`, "(?i)outage") ~ "Outage", 
                                                str_detect(`Title`, "(?i)TPM Chip") ~ "TPM Chip", 
                                                str_detect(`Title`, "(?i)NIC") ~ "Wireless Card", 
                                                str_detect(`Title`, "(?i)NTFS") ~ "NTFS", 
                                                str_detect(`Title`, "(?i)cold start") ~ "Cold Start", 
                                                str_detect(`Title`, "(?i)coldstart") ~ "Cold Start", 
                                                str_detect(`Title`, "(?i)backup battery") ~ "Backup Battery", 
                                                str_detect(`Title`, "(?i)BBU") ~ "Backup Battery", 
                                                str_detect(`Title`, "(?i)eaton") ~ "Backup Battery", 
                                                str_detect(`Title`, "(?i)reimage") ~ "Reimage", 
                                                str_detect(`Title`, "(?i)retalix") ~ "Retalix", 
                                                str_detect(`Title`, "(?i)gift card") ~ "Gift Card", 
                                                str_detect(`Title`, "(?i)latency") ~ "Latency", 
                                                str_detect(`Title`, "(?i)apple") ~ "Apple Pay", 
                                                str_detect(`Title`, "(?i)server down") ~ "Server Down", 
                                                str_detect(`Title`, "(?i)server connections") ~ "Server Connection", 
                                                str_detect(`Title`, "(?i)refund") ~ "Refund", 
                                                str_detect(`Title`, "(?i)HHU") ~ "Handheld Unit", 
                                                str_detect(`Title`, "(?i)UPS") ~ "Backup Battery", 
                                                str_detect(`Title`, "(?i)EBT") ~ "EBT", 
                                                str_detect(`Title`, "(?i)remote imager") ~ "Remote Imager", 
                                                str_detect(`Title`, "(?i)case discount") ~ "Discount", 
                                                str_detect(`Title`, "(?i)team member discount") ~ "Discount", 
                                                str_detect(`Title`, "(?i)bottle deposit") ~ "Discount", 
                                                str_detect(`Title`, "(?i)froze") ~ "Freezing", 
                                                str_detect(`Title`, "(?i)insufficient") ~ "Insufficient Priveleges", 
                                                str_detect(`Title`, "(?i)robologon") ~ "Robologin",
                                                str_detect(`Title`, "(?i)unexpected") ~ "Unexpected Shutdown", 
                                                str_detect(`Title`, "(?i)reboot") ~ "Unexpected Shutdown", 
                                                str_detect(`Title`, "(?i)virus") ~ "Virus Defnition", 
                                                str_detect(`Title`, "(?i)shutdown") ~ "Power", 
                                                str_detect(`Title`, "(?i)off") ~ "Power", 
                                                str_detect(`Title`, "(?i)upgrade") ~ "Upgrade", 
                                                str_detect(`Title`, "(?i)customer screen") ~ "Customer Display", 
                                                str_detect(`Title`, "(?i)lane conversion") ~ "Lane Setup", 
                                                str_detect(`Title`, "(?i)lane setup") ~ "Lane Setup", 
                                                str_detect(`Title`, "(?i)off") ~ "Power", 
                                                str_detect(`Title`, "(?i)boot media") ~ "Hard drive", 
                                                str_detect(`Title`, "(?i)blue screen") ~ "BSOD", 
                                                str_detect(`Title`, "(?i)bsod") ~ "BSOD", 
                                                str_detect(`Title`, "(?i)touchscreen") ~ "Cashier Display", 
                                                str_detect(`Title`, "(?i)close drawer") ~ "Cash Drawer Tickets", 
                                                str_detect(`Title`, "(?i)shut down") ~ "Power", 
                                                str_detect(`Title`, "(?i)power on") ~ "Power", 
                                                str_detect(`Title`, "(?i)register resets") ~ "Sales Audit", 
                                                str_detect(`Title`, "(?i)store tools") ~ "Store Tools", 
                                                str_detect(`Title`, "(?i)Tax") ~ "Tax", 
                                                str_detect(`Title`, "(?i)stuck token") ~ "Deadletter", 
                                                str_detect(`Title`, "(?i)deadletter") ~ "Deadletter", 
                                                str_detect(`Title`, "(?i)lane stuck") ~ "Freezing", 
                                                str_detect(`Title`, "(?i)drawer") ~ "Cash Drawer", 
                                                str_detect(`Title`, "(?i)chip reader") ~ "MSR", 
                                                str_detect(`Title`, "(?i)card reader") ~ "MSR", 
                                                str_detect(`Title`, "(?i)ctrl+alt+del") ~ "Autoadminlogon", 
                                                str_detect(`Title`, "(?i)crash") ~ "Power", 
                                                str_detect(`Title`, "(?i)crashed") ~ "Power", 
                                                str_detect(`Title`, "(?i)server connection") ~ "Server Connection", 
                                                str_detect(`Title`, "(?i)unhandled exception") ~ "Unhandled Exception", 
                                                str_detect(`Title`, "(?i)Ctrl+Alt+Del") ~ "Autoadminlogon", 
                                                str_detect(`Title`, "(?i)power issues") ~ "Power", 
                                                str_detect(`Title`, "(?i)cashier productivity") ~ "Cashier Productivity", 
                                                str_detect(`Title`, "(?i)Cartnado") ~ "Cartnado", 
                                                str_detect(`Title`, "(?i)EFT Approved") ~ "MSR", 
                                                str_detect(`Title`, "(?i)no price") ~ "Item Data", 
                                                str_detect(`Title`, "(?i)coupon") ~ "Coupon", 
                                                str_detect(`Title`, "(?i)windows upgrade") ~ "Deployment", 
                                                str_detect(`Title`, "(?i)extended menu") ~ "Extended Menu Options", 
                                                str_detect(`Title`, "(?i)transaction declined") ~ "MSR", 
                                                str_detect(`Title`, "(?i)store  network") ~ "Outage", 
                                                str_detect(`Title`, "(?i)PLU") ~ "Item Data", 
                                                str_detect(`Title`, "(?i)touch screen") ~ "Cashier Display", 
                                                str_detect(`Title`, "(?i)variance") ~ "Cash Up", 
                                                str_detect(`Title`, "(?i)touchpoint") ~ "Touchpoint", 
                                                str_detect(`Title`, "(?i)touch point") ~ "Touchpoint", 
                                                str_detect(`Title`, "(?i)double charge") ~ "Double Charge", 
                                                str_detect(`Title`, "(?i)double charged") ~ "Double Charge", 
                                                str_detect(`Title`, "(?i)charged twice") ~ "Double Charge", 
                                                str_detect(`Title`, "(?i)deployment") ~ "Deployment", 
                                                str_detect(`Title`, "(?i)windows update") ~ "Deployment", 
                                                str_detect(`Title`, "(?i)verify customer") ~ "MSR", 
                                                str_detect(`Title`, "(?i)out of balance") ~ "Sales Audit", 
                                                str_detect(`Title`, "(?i)ctrl") ~ "Ctrl+Alt+Del", 
                                                str_detect(`Title`, "(?i)freezing") ~ "Freezing", 
                                                str_detect(`Title`, "(?i)conversion") ~ "Lane Setup", 
                                                str_detect(`Title`, "(?i)store network") ~ "Outage", 
                                                str_detect(`Title`, "(?i)stylus") ~ "MSR Stylus", 
                                                str_detect(`Title`, "(?i)sales audit") ~ "Sales Audit", 
                                                str_detect(`Title`, "(?i)out of balance") ~ "Sales Audit", 
                                                str_detect(`Title`, "(?i)initial setup") ~ "Lane Setup", 
                                                str_detect(`Title`, "(?i)kiosk") ~ "Kiosk", 
                                                str_detect(`Title`, "(?i)connect to server") ~ "Server Connection", 
                                                str_detect(`Title`, "(?i)Network Down") ~ "Outage", 
                                                str_detect(`Title`, "(?i)build") ~ "Reimage", 
                                                str_detect(`Title`, "(?i)store down") ~ "Outage", 
                                                str_detect(`Title`, "(?i)Item") ~ "Item", 
                                                str_detect(`Title`, "(?i)powered down") ~ "Power", 
                                                str_detect(`Title`, "(?i)turning on") ~ "Power", 
                                                str_detect(`Title`, "(?i)pickup") ~ "Cash Up", 
                                                str_detect(`Title`, "(?i)balance report") ~ "Store Balance Report", 
                                                str_detect(`Title`, "(?i)menu options") ~ "Extended Menu Options", 
                                                str_detect(`Title`, "(?i)'opos' errors") ~ "NCR Loader", 
                                                str_detect(`Title`, "(?i)incorrect menu") ~ "Extended Menu Options", 
                                                str_detect(`Title`, "(?i)button") ~ "Keycap", 
                                                str_detect(`Title`, "(?i)rabbit") ~ "RabbitMQ", 
                                                str_detect(`Title`, "(?i)customer facing") ~ "Customer Display", 
                                                str_detect(`Title`, "(?i)opos trifecta") ~ "NCR Loader", 
                                                str_detect(`Title`, "(?i)bitlocker") ~ "Mainboard", 
                                                str_detect(`Title`, "(?i)QR") ~ "QR", 
                                                str_detect(`Title`, "(?i)pinpad") ~ "MSR", 
                                                str_detect(`Title`, "(?i)account") ~ "User Account", 
                                                str_detect(`Title`, "(?i)signal") ~ "MSR", 
                                                str_detect(`Title`, "(?i)unlock") ~ "User Account", 
                                                str_detect(`Title`, "(?i)user account") ~ "User Account", 
                                                str_detect(`Title`, "(?i)locked session") ~ "Locked Session", 
                                                str_detect(`Title`, "(?i)access") ~ "User Account", 
                                                str_detect(`Title`, "(?i)print") ~ "Printer", 
                                                str_detect(`Title`, "(?i)boot\\W?loop") ~ "Hard Drvie", 
                                                str_detect(`Title`, "(?i)boot looping") ~ "Hard Drive", 
                                                str_detect(`Title`, "(?i)bootloop") ~ "Hard Drive", 
                                                str_detect(`Title`, "(?i)bootlooping") ~ "Hard Drive", 
                                                str_detect(`Title`, "(?i)SBP") ~ "Stand Beside Payment", 
                                                str_detect(`Title`, "(?i)stand\\W?beside") ~ "Stand Beside Payment", 
                                                str_detect(`Title`, "(?i)void transaction") ~ "Stuck Transaction", 
                                                str_detect(`Title`, "(?i)unresponsive") ~ "Freezing", 
                                                str_detect(`Title`, "(?i)Pinpad") ~ "MSR", 
                                                str_detect(`Title`, "(?i)robo\\W?login") ~ "Robologin", 
                                                str_detect(`Title`, "(?i)robologin") ~ "Robologin", 
                                                str_detect(`Title`, "(?i)triad") ~ "NCR Loader", 
                                                str_detect(`Title`, "(?i)charging") ~ "Charging", 
                                                str_detect(`Title`, "(?i)pin reset") ~ "User Account", 
                                                str_detect(`Title`, "(?i)PIN reset") ~ "User Account", 
                                                str_detect(`Title`, "(?i)freezes") ~ "Freezing", 
                                                str_detect(`Title`, "(?i)role") ~ "User Account", 
                                                str_detect(`Title`, "(?i)roles") ~ "User Account", 
                                                str_detect(`Title`, "(?i)account unlock") ~ "User Account", 
                                                str_detect(`Title`, "(?i)account creation") ~ "User Account", 
                                                str_detect(`Title`, "(?i)pair") ~ "Bluetooth", 
                                                str_detect(`Title`, "(?i)pairing") ~ "Bluetooth",
                                                
                                                # my adds
                                                str_detect(`Title`, "(?i)eod") ~ "EOD",
                                                # str_detect(`Title`, "(?i)password\\W?reset") ~ "Password Reset",
                                                # str_detect(`Title`, "(?i)sign\\W?in") ~ "Sign In",
                                                TRUE ~ "(Uncategorized)"
                        )
)



# OUTPUT. CHANGE PATH TO YOUR PC OR SOMETHING
writexl::write_xlsx(x = test, path = "C:/Users/chris.jabr/Documents/peakseason.xlsx")